name = "ONSAS_docs"
uuid = "2aa56433-a529-4a65-aeaf-004c823dabb6"
#authors = ["mforets <mforets@gmail.com>", "jorgepz <jorgepz@fing.edu.uy>", "joaquinv <joaquinv@fing.edu.uy>"]
#version = "0.1.0"

# [deps]
#
# [compat]
# julia = "1"
#
# [extras]
# Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
# Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
#
# [targets]
# test = ["Plots", "Test"]
